name: comfe
channels:
  - conda-forge
dependencies:
  - python>=3.10
  - rust
  - maturin
  - pytest
  - conda-ecosystem-user-package-isolation
  - fenics-dolfinx=0.6.0
  - numpy
  - scipy
  - pydantic
  - pip
  - pip:
      - -e .
