[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
# Point to the Rust extension crate, relative to pyproject.toml location
bindings = "pyo3"
module-name = "comfe_py"  # This is the name you will import
manifest-path = "comfe-py/Cargo.toml"
features = ["pyo3/extension-module"]
python-source = "python"
# If you want to rename the Python package, set "name" here
# name = "mypackage"