name: Tests

on:
  push:
    branches-ignore:

  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  # Runs the workflow once per day at 3:15am
  #schedule:
  #  - cron: '3 15 * * *'

#env:
#  CACHE_NUMBER: 2  # increase to reset cache manually

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repo content
        uses: actions/checkout@v2
      
      - name: Setup Mambaforge
        uses: conda-incubator/setup-miniconda@v3
        with:
            #miniforge-variant: Mambaforge
            miniforge-version: latest
            activate-environment: comfe
            use-mamba: true

      - name: Update environment
        shell: bash -l {0}
        run: |
          mamba env update -n comfe -f environment.yml

      - name: Run tests
        shell: bash -l {0}
        run: |
          pytest

